version: '3'

tasks:
  server-dev:
    cmd: docker compose -f dockerfiles/dev/compose.yml up --build
    ignore_error: true
  server-dev-down:
    cmd: docker compose -f dockerfiles/dev/compose.yml down