version: '3'

tasks:
  server-dev:
    cmds:
      - docker compose -f dockerfiles/dev/compose.yml up --build
    ignore_error: true
  server-dev-down:
    cmds:
      - docker compose -f dockerfiles/dev/compose.yml down