name: Server

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Move to server/
        run: cd server
      - name: Format
        uses: go fmt ./...
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Move to server/
        run: cd server
      - name: Build
        uses: go build -v ./...
        
  